name: Greet on New Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Issue Creator
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.payload.issue.user.login;
            const issueNumber = context.payload.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            const { data: events } = await github.rest.issues.listEventsForTimeline({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber,
            });

            const isFirstTime = !events.some(event => 
              event.actor?.login === username && event.event === "commented"
            );

            let message = "";

            if (isFirstTime) {
              message = `ğŸ‘‹ **Hi @${username}!**\n\nWelcome and thanks for creating your first issue in this repository!\n Before creating pr please update your local repo to avoid the conflicts. ğŸ‰\n\nPlease make sure to:\n- Follow our [Contribution Guidelines](https://github.com/${repoOwner}/${repoName}/blob/main/CONTRIBUTION.md)\n- Read our [Code of Conduct](https://github.com/${repoOwner}/${repoName}/blob/main/CODE_OF_CONDUCT.md)\n- Star the repo ğŸŒŸ if you like the project!\n\nğŸ“¢ Stay connected with us on:\n- [Instagram](https://instagram.com/vaibhav_be_able)\n- [LinkedIn](https://linkedin.com/in/vaibhavbabele)\n- [GitHub Discussions](https://github.com/${repoOwner}/${repoName}/discussions)\n[Discord](https://discord.gg/cYkT2F3v)\nHappy contributing! ğŸš€ \nPlease wait while we review your issue it take some time also share the issue link on [Discord](https://discord.gg/cYkT2F3v)\n @meetarora10 , @camren88 , @Withvansh please review this issue.\n\n if follow the guideline and fit to project then label according to issue otherwise close the issue.`;
            } else {
              message = `Thanks @${username} for opening this issue again! We appreciate your continued contributions.\n\n Before creating pr please update your local repo to avoid the conflicts. ğŸ˜Š\n\nPlease wait while we review your issue it take some time also share the issue link on [Discord](https://discord.gg/cYkT2F3v)\n , @meetarora10 ,@camren88 @Withvansh please review this issue . \n\n if follow the guideline and fit to project then label according to issue otherwise close the issue.ğŸ”`;
            }

            await github.rest.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber,
              body: message
            });
